### ISSUE TITLE
Ifc element color

### ISSUE THREAD

**Issue by JanoSlivka** [opensourceBIM/BIMsurfer#53]
Hello,

why do the walls have different colors? In BimSurfer v1 have same color.

Thanks

![bimSurfer_v3](https://user-images.githubusercontent.com/44858488/65439730-f1015d00-de27-11e9-8076-c590e2b2ca3c.PNG)
![bimSurfer_v1](https://user-images.githubusercontent.com/44858488/65439732-f1015d00-de27-11e9-8490-bf4cfb6787a1.PNG)
[walls.zip](https://github.com/opensourceBIM/BIMsurfer/files/3642903/walls.zip)

**Comment by rubendel** [comment]
There was an issue with the oct-encoding of normals. This issue is still there, so I added another option which is disabled by default called "octEncodeNormals". This requires a new version of BinarySerializers as well. Oct-encoding is not very important (saves one more byte per normal) and will be looked at later.

**Comment by JanoSlivka** [comment]
Ok, thanks. So it will be available in the new version of BimServer and BimSurfer?

**Comment by JanoSlivka** [comment]
Works fine.
